version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      action-dependencies:
        dependency-type: "production"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      npm-dependencies:
        dependency-type: "production"
